### ISSUE TITLE
 python setup.py egg_info did not run successfully 和 Encountered error while generating package metadata.

### ISSUE THREAD

**Issue by 2949984428** [WSH032/kohya-config-webui#6]
Cloning into '/content/sd-scripts'...
remote: Enumerating objects: 2808, done.
remote: Counting objects: 100% (1021/1021), done.
remote: Compressing objects: 100% (276/276), done.
remote: Total 2808 (delta 842), reused 847 (delta 745), pack-reused 1787
Receiving objects: 100% (2808/2808), 3.28 MiB | 4.97 MiB/s, done.
Resolving deltas: 100% (1922/1922), done.
Cloning into '/content/kohya-config-webui'...
remote: Enumerating objects: 118, done.
remote: Counting objects: 100% (118/118), done.
remote: Compressing objects: 100% (91/91), done.
remote: Total 118 (delta 58), reused 53 (delta 22), pack-reused 0
Receiving objects: 100% (118/118), 67.27 KiB | 13.45 MiB/s, done.
Resolving deltas: 100% (58/58), done.
torch安装中
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 108.2/108.2 MB 8.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 123.8/123.8 MB 8.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 123.6/123.6 MB 7.9 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 50.9/50.9 MB 12.9 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 292.5/292.5 kB 33.1 MB/s eta 0:00:00
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  Preparing metadata (setup.py) ... error
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
torch安装完成
kohya依赖安装中

**Comment by WSH032** [comment]
收到。
colab昨天更新了`torch2.0.0` -> `torch2.0.1`， 但是xformer和它不兼容现在，所以导致了上述问题的发生。

---

目前有两个解决方案：

## 降级torch
```diff
-!pip -q install torch torchvision xformers triton
+!pip -q install torch==2.0.0 torchvision xformers triton
```
*缺点是安装时间多了3~4分钟*

## 训练时不使用xfomer
torch2.0.1及相关依赖colab已经安装好了，什么代码也不用动，训练时候别开xformer就行
*缺点是显存占用变高*

---

我一会更新的时候会采用第一种方法。
你可能会注意到安装时会有一些红色警告，例如
`torchaudio 2.0.2+cu118 requires torch==2.0.1, but you have torch 2.0.0 which is incompatible.`
这个不影响训练（至少我没观察到）

**Comment by 2949984428** [comment]
> 收到。 colab昨天更新了`torch2.0.0` -> `torch2.0.1`， 但是xformer和它不兼容现在，所以导致了上述问题的发生。
> 
> 目前有两个解决方案：
> 
> ## 降级torch
> ```diff
> -!pip -q install torch torchvision xformers triton
> +!pip -q install torch==2.0.0 torchvision xformers triton
> ```
> 
> _缺点是安装时间多了3~4分钟_
> 
> ## 训练时不使用xfomer
> torch2.0.1及相关依赖colab已经安装好了，什么代码也不用动，训练时候别开xformer就行 _缺点是显存占用变高_
> 
> 我一会更新的时候会采用第一种方法。 你可能会注意到安装时会有一些红色警告，例如 `torchaudio 2.0.2+cu118 requires torch==2.0.1, but you have torch 2.0.0 which is incompatible.` 这个不影响训练（至少我没观察到）

**Comment by 2949984428** [comment]
感谢 另外 b站求继续更新
